package com.hanjisang.pis.integration.gateway;

public enum IntegrationCapability {
    PATIENT_QUERY,
    ENCOUNTER_QUERY,
    ORDER_RECEIVE,
    FEE_STATUS_SYNC,
    REPORT_DELIVERY,
    REPORT_VIEW,
    CLINICAL_INFORMATION_QUERY,
    SPECIMEN_RECEIVE,
    RESULT_RECEIVE,
    CLINICAL_RESULT_NOTIFICATION,
    PROVINCE_PLATFORM,
    REGIONAL_PLATFORM
}
